sudo: required
services:
    - docker

before_install:
    - docker build -t ankitcagarwal/multi-docker -f ./client/Dockerfile.dev ./client

script:
    -  docker run -e CI=true ankitcagarwal/multi-docker npm test

after_success:
    - docker build -t ankitcagarwal/multi-client ./client
    - docker build -t ankitcagarwal/multi-nginx ./nginx
    - docker build -t ankitcagarwal/multi-server ./server
    - docker build -t ankitcagarwal/multi-worker ./worker

#login to docker cli
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
 
#Take all the images and push to docker hub
    - docker push ankitcagarwal/multi-client
    - docker push ankitcagarwal/multi-nginx
    - docker push ankitcagarwal/multi-server
    - docker push ankitcagarwal/multi-worker

deploy:
    provider: elasticbeanstalk
    region: us-east-2
    app: multi-docker
    env: MultiDocker-env
    bucket-name: elasticbeanstalk-us-east-2-642433476522
    bucket-path: docker_multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY